# Generated by Django 4.0.4 on 2022-05-09 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Poster_link', models.CharField(max_length=512)),
                ('Series_Title', models.CharField(max_length=512)),
                ('Released_Year', models.CharField(max_length=128)),
                ('Certificate', models.CharField(max_length=100)),
                ('Runtime', models.CharField(max_length=128)),
                ('Genre', models.CharField(max_length=128)),
                ('IMDB_Rating', models.CharField(max_length=128)),
                ('Overview', models.CharField(max_length=2000)),
                ('Meta_score', models.CharField(max_length=100)),
                ('Director', models.CharField(max_length=100)),
                ('star1', models.CharField(blank=True, max_length=100, null=True)),
                ('star2', models.CharField(blank=True, max_length=100, null=True)),
                ('star3', models.CharField(blank=True, max_length=100, null=True)),
                ('star4', models.CharField(blank=True, max_length=100, null=True)),
                ('No_of_Votes', models.CharField(max_length=100)),
                ('Gross', models.CharField(max_length=110)),
            ],
            options={
                'verbose_name_plural': 'movies',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Recommendations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, max_length=526, null=True)),
                ('date_recommended', models.DateField(auto_now_add=True)),
                ('is_watched_by_receiver', models.BooleanField(blank=True, null=True)),
                ('date_watched_by_receiver', models.DateField(blank=True, null=True)),
                ('receiver_rating', models.CharField(blank=True, choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], max_length=1, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='movies_app.movie')),
                ('recommend_to', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='recommend_to', to=settings.AUTH_USER_MODEL)),
                ('recommender', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='recommender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'recommendations',
            },
        ),
        migrations.CreateModel(
            name='My_Watch_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], max_length=1)),
                ('review_msg', models.CharField(default='Liked', max_length=1024)),
                ('watched_date', models.DateTimeField()),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(blank=True, null=True)),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='movies_app.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'watch_list',
            },
        ),
    ]
